from __future__ import annotations

from typing import Any, Protocol

from pallattu_ai_assistant.domain import (
    AssistantReply,
    AudioBuffer,
    CapturedUtterance,
    ImageFrame,
)


class PerceptionPort(Protocol):
    def start(self) -> None: ...
    def close(self) -> None: ...
    def wait_for_wake_word(self) -> None: ...
    def capture_utterance(self, start_timeout_seconds: float) -> CapturedUtterance | None: ...


class VoiceAIPort(Protocol):
    def handle(self, audio: AudioBuffer) -> AssistantReply: ...


class VisionPort(Protocol):
    """Portable boundary for obtaining a still frame from an available camera."""

    def available(self) -> bool: ...
    def describe_source(self) -> str: ...
    def capture(self) -> ImageFrame: ...


class VisionAnalysisPort(Protocol):
    """Portable boundary for interpreting a captured frame."""

    def analyze(self, frame: ImageFrame, prompt: str) -> str: ...


class ActuatorPort(Protocol):
    """Low-level robot actuator boundary. Never expose this directly to the model."""

    def available(self) -> bool: ...
    def describe(self) -> str: ...
    def set_servo_angle(self, channel: int, angle_degrees: float) -> None: ...
    def drive(self, left_speed: float, right_speed: float, duration_seconds: float) -> None: ...
    def stop(self) -> None: ...


class ToolPort(Protocol):
    """Application-facing capability boundary for safe local/external tools."""

    def definitions(self) -> list[dict[str, Any]]: ...
    def execute(self, name: str, arguments: dict[str, Any]) -> dict[str, Any]: ...


class MemoryPort(Protocol):
    """Application-facing boundary for persistent conversation and long-term memory."""

    def recent_messages(self, limit: int = 8) -> list[dict[str, str]]: ...
    def append_message(self, role: str, content: str) -> None: ...
    def prune_conversations(self, max_messages: int | None = None) -> int: ...
    def clear_conversations(self) -> int: ...
    def clear_memories(self) -> int: ...
    def stats(self) -> dict[str, Any]: ...
    def search(self, query: str, limit: int = 5) -> list[str]: ...
    def remember(self, fact: str) -> dict[str, Any]: ...
    def forget(self, query: str) -> dict[str, Any]: ...
    def list_memories(self, limit: int = 20) -> list[str]: ...


class WakeAcknowledgementPort(Protocol):
    def acknowledge(self) -> None: ...


class AudioOutputPort(Protocol):
    def play(self, audio: AudioBuffer) -> None: ...


class MetricsPort(Protocol):
    def record(self, reply: AssistantReply, captured: CapturedUtterance, elapsed_seconds: float) -> None: ...
